# Generated by Django 5.2.3 on 2025-12-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_authore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authore',
            new_name='author',
        ),
    ]
