# Generated by Django 5.2.3 on 2025-12-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='authore',
            new_name='author',
        ),
    ]
